services:

  #  nginx:
  #  db:
  #    image: postgres
  #    restart: always
  #      # set shared memory limit when using docker compose
  #      # shm_size: 128mb
  #      # or set shared memory limit when deploy via swarm stack
  #    #volumes:
  #      #  - type: tmpfs
  #      #    target: /dev/shm
  #      #    tmpfs:
  #      #      size: 134217728 # 128*2^20 bytes = 128Mb
  #    environment:
  #      POSTGRES_PASSWORD: qwerty

  app:
    image: ghcr.io/gwinbleid86/movie_review_java25_image:latest
    container_name: movie_review_container
    ports:
      - "8089:8089"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env
#    depends_on:
#      - db